package app54;

public class M35 {
	public static void main(String[] args) {
		try {
			
		}
		catch(ArithmeticException ex) {
			
		}
		catch(NullPointerException ex) {
			
		}
		finally {
			
		}
		System.out.println("done");
	}
}
//it compile successfully b/c one try should take the multiple catch allow after catch finally allow b/c finally is a last block