package app54;

public class M40 {
	public static void main(String[] args) {
//		catch(ArithmeticException ex) {
//			
//		}
//		finally {
//			
//		}
	}
}
//finally and catch both together can not be develop without the try 
//it give compilation error
//it is not possible